### ISSUE TITLE
composer install error.

### ISSUE THREAD

**Issue by hgati** [greenrivers/magento-module-webp#1]
Doesn't it support PHP 8.2.4

```
$ composer require greenrivers/webp
Package greenrivers/webp has requirements incompatible with your PHP version, PHP extensions and Composer version:         
    - greenrivers/webp 1.0.0 requires php ~7.1.0||~7.2.0||~7.3.0||~7.4.0 which does not match your installed version 8.2.4. 
```

**Comment by MajorKuprich** [comment]
Hello @hgati,

Thanks for Your ticket.
I've added compatibility to Magento 2.4+ version, check it please.
New version released: https://github.com/greenrivers/magento-module-webp/releases/tag/1.1.0

Regards

**Comment by hgati** [comment]
I'm using Magento 2.4.6 / php 8.2.4
Thanks for great extension.

When installing Composer, I must put the version name of 1.1.0 to install the latest version.
Even if I install with version 1.1.0, there will be a compatibility conflict with the vips version.

![](https://i.ibb.co/7p5R38s/aaa.png)
```
$ composer require greenrivers/webp:1.1.0
./composer.json has been updated
Running composer update greenrivers/webp
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires greenrivers/webp 1.1.0 -> satisfiable by greenrivers/webp[1.1.0].
    - greenrivers/webp 1.1.0 requires jcupitt/vips ~1.0.5 -> found jcupitt/vips[v1.0.5, ..., v1.0.10] but it conflicts with your root composer.json require (^2.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

So I downgraded the vips version to 1.0.5 and somehow the installation was completed.

```
$ composer require jcupitt/vips:1.0.5
$ composer require greenrivers/webp:1.1.0
```

Now I went to Store > Configuration to set up.

![](https://i.ibb.co/hsMcBpL/ddd.png)

Then the following error occurs.
need /media/catalog/product/cache directory on save product.

![](https://i.ibb.co/SmrmrWq/ccc.png)

So I created cache directory manually. and then It works fine. - product save

![](https://i.ibb.co/DDXVzSJ/webp.png)

but, there is an issue. 
If I delete the image again and try to save the product, the following warning appears.

![](https://i.ibb.co/2Pf63Rb/remove.png)

![](https://i.ibb.co/HCFjd9W/kkk.png)

So I researched the greenrivers directory.
Even if I delete the image of the product, the webp image is not automatically deleted and remains in the magento/pub/media/greenrivers/webp/catalog/product/2/0 directory.

As a result, It broken image on frontend.

![](https://i.ibb.co/fnRr1tn/remove2.png)

On the other hand  I am getting an unknown error in admin menu with creating infinite media elements on the left. (Content > Convertion)

![](https://i.ibb.co/Bw70fmr/bbb.png)

So I've researched chrome console. 404 error.

![](https://i.ibb.co/fxBb2P9/tree.png)

I'm using **custom admin route** NOT youdomain.com/admin.
I'm using an admin route like this.
`yourdomain.com/<my_custom_admin_route>/greenrivers_webp/conversion/treenode?isAjax=true`

Also only webp works fine, neither cwebp nor vips.
Cwebp doesn't show any error on save product, but actually no webp file is created.
If set to Vips, an error occurs with a blank page when saving the product.

![](https://i.ibb.co/zZmtnYp/yyy.png)

**Comment by hgati** [comment]
I finally found an extension that solved all the issues. 
I didn't know such an extension existed.

https://packagist.org/packages/yireo/magento2-webp2

**Comment by hgati** [comment]
I finally found an extension for Magento2 WebP support that solved all the issues.
I didn't know such an extension existed.
This extension works very well with Magento 2.4.6 / php 8.2.4

https://packagist.org/packages/yireo/magento2-webp2
